### PR TITLE
Voc safe decode

### PR DESCRIPTION
**Pull request by boulch**
Encoding issue.

### CODE REVIEW

**Comment by gbastien** [comment]
Hi @tdesvenain 

could you please have a look?

Thank you!

Gauthier

**Comment by gbastien** [comment]
Hi @boulch 

could you please add a test for this?

Thank you,

Gauthier

**Comment by boulch** [comment]
Hi @gbastien 
Test : Done ! 

approve now? :-)

**Review by gbastien — COMMENTED** [review]
Merged!

Adaptations in code avoid multiple return of value and tests are passing...

**Pull request merged**
